spring:
  application:
    name: Messenger
  datasource:
    url: jdbc:postgresql://localhost:8080/Messenger
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true